// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sofa_pbrpc_meta.proto

package com.baidu.brpc.protocol.sofa;

public final class SofaRpcProto {
  private SofaRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code brpc.policy.SofaCompressType}
   */
  public enum SofaCompressType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SOFA_COMPRESS_TYPE_NONE = 0;</code>
     */
    SOFA_COMPRESS_TYPE_NONE(0, 0),
    /**
     * <code>SOFA_COMPRESS_TYPE_GZIP = 1;</code>
     */
    SOFA_COMPRESS_TYPE_GZIP(1, 1),
    /**
     * <code>SOFA_COMPRESS_TYPE_ZLIB = 2;</code>
     */
    SOFA_COMPRESS_TYPE_ZLIB(2, 2),
    /**
     * <code>SOFA_COMPRESS_TYPE_SNAPPY = 3;</code>
     */
    SOFA_COMPRESS_TYPE_SNAPPY(3, 3),
    /**
     * <code>SOFA_COMPRESS_TYPE_LZ4 = 4;</code>
     */
    SOFA_COMPRESS_TYPE_LZ4(4, 4),
    ;

    /**
     * <code>SOFA_COMPRESS_TYPE_NONE = 0;</code>
     */
    public static final int SOFA_COMPRESS_TYPE_NONE_VALUE = 0;
    /**
     * <code>SOFA_COMPRESS_TYPE_GZIP = 1;</code>
     */
    public static final int SOFA_COMPRESS_TYPE_GZIP_VALUE = 1;
    /**
     * <code>SOFA_COMPRESS_TYPE_ZLIB = 2;</code>
     */
    public static final int SOFA_COMPRESS_TYPE_ZLIB_VALUE = 2;
    /**
     * <code>SOFA_COMPRESS_TYPE_SNAPPY = 3;</code>
     */
    public static final int SOFA_COMPRESS_TYPE_SNAPPY_VALUE = 3;
    /**
     * <code>SOFA_COMPRESS_TYPE_LZ4 = 4;</code>
     */
    public static final int SOFA_COMPRESS_TYPE_LZ4_VALUE = 4;


    public final int getNumber() { return value; }

    public static SofaCompressType valueOf(int value) {
      switch (value) {
        case 0: return SOFA_COMPRESS_TYPE_NONE;
        case 1: return SOFA_COMPRESS_TYPE_GZIP;
        case 2: return SOFA_COMPRESS_TYPE_ZLIB;
        case 3: return SOFA_COMPRESS_TYPE_SNAPPY;
        case 4: return SOFA_COMPRESS_TYPE_LZ4;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SofaCompressType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SofaCompressType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SofaCompressType>() {
            public SofaCompressType findValueByNumber(int number) {
              return SofaCompressType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.baidu.brpc.protocol.sofa.SofaRpcProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final SofaCompressType[] VALUES = values();

    public static SofaCompressType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SofaCompressType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brpc.policy.SofaCompressType)
  }

  public interface SofaRpcMetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .brpc.policy.SofaRpcMeta.Type type = 1;
    /**
     * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
     */
    com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type getType();

    // required uint64 sequence_id = 2;
    /**
     * <code>required uint64 sequence_id = 2;</code>
     *
     * <pre>
     * Message sequence id.
     * </pre>
     */
    boolean hasSequenceId();
    /**
     * <code>required uint64 sequence_id = 2;</code>
     *
     * <pre>
     * Message sequence id.
     * </pre>
     */
    long getSequenceId();

    // optional string method = 100;
    /**
     * <code>optional string method = 100;</code>
     *
     * <pre>
     * Method full name.
     * For io.brpc.example.example: "test.HelloService.GreetMethod"
     * </pre>
     */
    boolean hasMethod();
    /**
     * <code>optional string method = 100;</code>
     *
     * <pre>
     * Method full name.
     * For io.brpc.example.example: "test.HelloService.GreetMethod"
     * </pre>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 100;</code>
     *
     * <pre>
     * Method full name.
     * For io.brpc.example.example: "test.HelloService.GreetMethod"
     * </pre>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    // optional bool failed = 200;
    /**
     * <code>optional bool failed = 200;</code>
     *
     * <pre>
     * Set as true if the call is failed.
     * </pre>
     */
    boolean hasFailed();
    /**
     * <code>optional bool failed = 200;</code>
     *
     * <pre>
     * Set as true if the call is failed.
     * </pre>
     */
    boolean getFailed();

    // optional int32 error_code = 201;
    /**
     * <code>optional int32 error_code = 201;</code>
     *
     * <pre>
     * The error code if the call is failed.
     * </pre>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 error_code = 201;</code>
     *
     * <pre>
     * The error code if the call is failed.
     * </pre>
     */
    int getErrorCode();

    // optional string reason = 202;
    /**
     * <code>optional string reason = 202;</code>
     *
     * <pre>
     * The error reason if the call is failed.
     * </pre>
     */
    boolean hasReason();
    /**
     * <code>optional string reason = 202;</code>
     *
     * <pre>
     * The error reason if the call is failed.
     * </pre>
     */
    java.lang.String getReason();
    /**
     * <code>optional string reason = 202;</code>
     *
     * <pre>
     * The error reason if the call is failed.
     * </pre>
     */
    com.google.protobuf.ByteString
        getReasonBytes();

    // optional .brpc.policy.SofaCompressType compress_type = 300;
    /**
     * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
     *
     * <pre>
     * Set the request/response compress type.
     * </pre>
     */
    boolean hasCompressType();
    /**
     * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
     *
     * <pre>
     * Set the request/response compress type.
     * </pre>
     */
    com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType getCompressType();

    // optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;
    /**
     * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
     *
     * <pre>
     * Set the response compress type of user expected.
     * </pre>
     */
    boolean hasExpectedResponseCompressType();
    /**
     * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
     *
     * <pre>
     * Set the response compress type of user expected.
     * </pre>
     */
    com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType getExpectedResponseCompressType();
  }
  /**
   * Protobuf type {@code brpc.policy.SofaRpcMeta}
   */
  public static final class SofaRpcMeta extends
      com.google.protobuf.GeneratedMessage
      implements SofaRpcMetaOrBuilder {
    // Use SofaRpcMeta.newBuilder() to construct.
    private SofaRpcMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SofaRpcMeta(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SofaRpcMeta defaultInstance;
    public static SofaRpcMeta getDefaultInstance() {
      return defaultInstance;
    }

    public SofaRpcMeta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SofaRpcMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type value = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequenceId_ = input.readUInt64();
              break;
            }
            case 802: {
              bitField0_ |= 0x00000004;
              method_ = input.readBytes();
              break;
            }
            case 1600: {
              bitField0_ |= 0x00000008;
              failed_ = input.readBool();
              break;
            }
            case 1608: {
              bitField0_ |= 0x00000010;
              errorCode_ = input.readInt32();
              break;
            }
            case 1618: {
              bitField0_ |= 0x00000020;
              reason_ = input.readBytes();
              break;
            }
            case 2400: {
              int rawValue = input.readEnum();
              com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType value = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(300, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                compressType_ = value;
              }
              break;
            }
            case 2408: {
              int rawValue = input.readEnum();
              com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType value = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(301, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                expectedResponseCompressType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.brpc.protocol.sofa.SofaRpcProto.internal_static_brpc_policy_SofaRpcMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.brpc.protocol.sofa.SofaRpcProto.internal_static_brpc_policy_SofaRpcMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.class, com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Builder.class);
    }

    public static com.google.protobuf.Parser<SofaRpcMeta> PARSER =
        new com.google.protobuf.AbstractParser<SofaRpcMeta>() {
      public SofaRpcMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SofaRpcMeta(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SofaRpcMeta> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code brpc.policy.SofaRpcMeta.Type}
     *
     * <pre>
     * Message type.
     * </pre>
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST = 0;</code>
       */
      REQUEST(0, 0),
      /**
       * <code>RESPONSE = 1;</code>
       */
      RESPONSE(1, 1),
      ;

      /**
       * <code>REQUEST = 0;</code>
       */
      public static final int REQUEST_VALUE = 0;
      /**
       * <code>RESPONSE = 1;</code>
       */
      public static final int RESPONSE_VALUE = 1;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:brpc.policy.SofaRpcMeta.Type)
    }

    private int bitField0_;
    // required .brpc.policy.SofaRpcMeta.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type type_;
    /**
     * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
     */
    public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type getType() {
      return type_;
    }

    // required uint64 sequence_id = 2;
    public static final int SEQUENCE_ID_FIELD_NUMBER = 2;
    private long sequenceId_;
    /**
     * <code>required uint64 sequence_id = 2;</code>
     *
     * <pre>
     * Message sequence id.
     * </pre>
     */
    public boolean hasSequenceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 sequence_id = 2;</code>
     *
     * <pre>
     * Message sequence id.
     * </pre>
     */
    public long getSequenceId() {
      return sequenceId_;
    }

    // optional string method = 100;
    public static final int METHOD_FIELD_NUMBER = 100;
    private java.lang.Object method_;
    /**
     * <code>optional string method = 100;</code>
     *
     * <pre>
     * Method full name.
     * For io.brpc.example.example: "test.HelloService.GreetMethod"
     * </pre>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string method = 100;</code>
     *
     * <pre>
     * Method full name.
     * For io.brpc.example.example: "test.HelloService.GreetMethod"
     * </pre>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method = 100;</code>
     *
     * <pre>
     * Method full name.
     * For io.brpc.example.example: "test.HelloService.GreetMethod"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool failed = 200;
    public static final int FAILED_FIELD_NUMBER = 200;
    private boolean failed_;
    /**
     * <code>optional bool failed = 200;</code>
     *
     * <pre>
     * Set as true if the call is failed.
     * </pre>
     */
    public boolean hasFailed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool failed = 200;</code>
     *
     * <pre>
     * Set as true if the call is failed.
     * </pre>
     */
    public boolean getFailed() {
      return failed_;
    }

    // optional int32 error_code = 201;
    public static final int ERROR_CODE_FIELD_NUMBER = 201;
    private int errorCode_;
    /**
     * <code>optional int32 error_code = 201;</code>
     *
     * <pre>
     * The error code if the call is failed.
     * </pre>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 error_code = 201;</code>
     *
     * <pre>
     * The error code if the call is failed.
     * </pre>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    // optional string reason = 202;
    public static final int REASON_FIELD_NUMBER = 202;
    private java.lang.Object reason_;
    /**
     * <code>optional string reason = 202;</code>
     *
     * <pre>
     * The error reason if the call is failed.
     * </pre>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string reason = 202;</code>
     *
     * <pre>
     * The error reason if the call is failed.
     * </pre>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reason_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reason = 202;</code>
     *
     * <pre>
     * The error reason if the call is failed.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .brpc.policy.SofaCompressType compress_type = 300;
    public static final int COMPRESS_TYPE_FIELD_NUMBER = 300;
    private com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType compressType_;
    /**
     * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
     *
     * <pre>
     * Set the request/response compress type.
     * </pre>
     */
    public boolean hasCompressType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
     *
     * <pre>
     * Set the request/response compress type.
     * </pre>
     */
    public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType getCompressType() {
      return compressType_;
    }

    // optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;
    public static final int EXPECTED_RESPONSE_COMPRESS_TYPE_FIELD_NUMBER = 301;
    private com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType expectedResponseCompressType_;
    /**
     * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
     *
     * <pre>
     * Set the response compress type of user expected.
     * </pre>
     */
    public boolean hasExpectedResponseCompressType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
     *
     * <pre>
     * Set the response compress type of user expected.
     * </pre>
     */
    public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType getExpectedResponseCompressType() {
      return expectedResponseCompressType_;
    }

    private void initFields() {
      type_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type.REQUEST;
      sequenceId_ = 0L;
      method_ = "";
      failed_ = false;
      errorCode_ = 0;
      reason_ = "";
      compressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
      expectedResponseCompressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequenceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(100, getMethodBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(200, failed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(201, errorCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(202, getReasonBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(300, compressType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(301, expectedResponseCompressType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(100, getMethodBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(200, failed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(201, errorCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(202, getReasonBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(300, compressType_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(301, expectedResponseCompressType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code brpc.policy.SofaRpcMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.brpc.protocol.sofa.SofaRpcProto.internal_static_brpc_policy_SofaRpcMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.brpc.protocol.sofa.SofaRpcProto.internal_static_brpc_policy_SofaRpcMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.class, com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Builder.class);
      }

      // Construct using com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        sequenceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        failed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        reason_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        compressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
        bitField0_ = (bitField0_ & ~0x00000040);
        expectedResponseCompressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.brpc.protocol.sofa.SofaRpcProto.internal_static_brpc_policy_SofaRpcMeta_descriptor;
      }

      public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta getDefaultInstanceForType() {
        return com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.getDefaultInstance();
      }

      public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta build() {
        com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta buildPartial() {
        com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta result = new com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequenceId_ = sequenceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.failed_ = failed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.reason_ = reason_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.compressType_ = compressType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.expectedResponseCompressType_ = expectedResponseCompressType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta) {
          return mergeFrom((com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta other) {
        if (other == com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSequenceId()) {
          setSequenceId(other.getSequenceId());
        }
        if (other.hasMethod()) {
          bitField0_ |= 0x00000004;
          method_ = other.method_;
          onChanged();
        }
        if (other.hasFailed()) {
          setFailed(other.getFailed());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasReason()) {
          bitField0_ |= 0x00000020;
          reason_ = other.reason_;
          onChanged();
        }
        if (other.hasCompressType()) {
          setCompressType(other.getCompressType());
        }
        if (other.hasExpectedResponseCompressType()) {
          setExpectedResponseCompressType(other.getExpectedResponseCompressType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSequenceId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .brpc.policy.SofaRpcMeta.Type type = 1;
      private com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type type_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type.REQUEST;
      /**
       * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
       */
      public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type getType() {
        return type_;
      }
      /**
       * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
       */
      public Builder setType(com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .brpc.policy.SofaRpcMeta.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaRpcMeta.Type.REQUEST;
        onChanged();
        return this;
      }

      // required uint64 sequence_id = 2;
      private long sequenceId_ ;
      /**
       * <code>required uint64 sequence_id = 2;</code>
       *
       * <pre>
       * Message sequence id.
       * </pre>
       */
      public boolean hasSequenceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 sequence_id = 2;</code>
       *
       * <pre>
       * Message sequence id.
       * </pre>
       */
      public long getSequenceId() {
        return sequenceId_;
      }
      /**
       * <code>required uint64 sequence_id = 2;</code>
       *
       * <pre>
       * Message sequence id.
       * </pre>
       */
      public Builder setSequenceId(long value) {
        bitField0_ |= 0x00000002;
        sequenceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 sequence_id = 2;</code>
       *
       * <pre>
       * Message sequence id.
       * </pre>
       */
      public Builder clearSequenceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceId_ = 0L;
        onChanged();
        return this;
      }

      // optional string method = 100;
      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 100;</code>
       *
       * <pre>
       * Method full name.
       * For io.brpc.example.example: "test.HelloService.GreetMethod"
       * </pre>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string method = 100;</code>
       *
       * <pre>
       * Method full name.
       * For io.brpc.example.example: "test.HelloService.GreetMethod"
       * </pre>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 100;</code>
       *
       * <pre>
       * Method full name.
       * For io.brpc.example.example: "test.HelloService.GreetMethod"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 100;</code>
       *
       * <pre>
       * Method full name.
       * For io.brpc.example.example: "test.HelloService.GreetMethod"
       * </pre>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 100;</code>
       *
       * <pre>
       * Method full name.
       * For io.brpc.example.example: "test.HelloService.GreetMethod"
       * </pre>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 100;</code>
       *
       * <pre>
       * Method full name.
       * For io.brpc.example.example: "test.HelloService.GreetMethod"
       * </pre>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        method_ = value;
        onChanged();
        return this;
      }

      // optional bool failed = 200;
      private boolean failed_ ;
      /**
       * <code>optional bool failed = 200;</code>
       *
       * <pre>
       * Set as true if the call is failed.
       * </pre>
       */
      public boolean hasFailed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool failed = 200;</code>
       *
       * <pre>
       * Set as true if the call is failed.
       * </pre>
       */
      public boolean getFailed() {
        return failed_;
      }
      /**
       * <code>optional bool failed = 200;</code>
       *
       * <pre>
       * Set as true if the call is failed.
       * </pre>
       */
      public Builder setFailed(boolean value) {
        bitField0_ |= 0x00000008;
        failed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool failed = 200;</code>
       *
       * <pre>
       * Set as true if the call is failed.
       * </pre>
       */
      public Builder clearFailed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        failed_ = false;
        onChanged();
        return this;
      }

      // optional int32 error_code = 201;
      private int errorCode_ ;
      /**
       * <code>optional int32 error_code = 201;</code>
       *
       * <pre>
       * The error code if the call is failed.
       * </pre>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 error_code = 201;</code>
       *
       * <pre>
       * The error code if the call is failed.
       * </pre>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 error_code = 201;</code>
       *
       * <pre>
       * The error code if the call is failed.
       * </pre>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000010;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 error_code = 201;</code>
       *
       * <pre>
       * The error code if the call is failed.
       * </pre>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      // optional string reason = 202;
      private java.lang.Object reason_ = "";
      /**
       * <code>optional string reason = 202;</code>
       *
       * <pre>
       * The error reason if the call is failed.
       * </pre>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string reason = 202;</code>
       *
       * <pre>
       * The error reason if the call is failed.
       * </pre>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reason = 202;</code>
       *
       * <pre>
       * The error reason if the call is failed.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reason = 202;</code>
       *
       * <pre>
       * The error reason if the call is failed.
       * </pre>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 202;</code>
       *
       * <pre>
       * The error reason if the call is failed.
       * </pre>
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000020);
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 202;</code>
       *
       * <pre>
       * The error reason if the call is failed.
       * </pre>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        reason_ = value;
        onChanged();
        return this;
      }

      // optional .brpc.policy.SofaCompressType compress_type = 300;
      private com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType compressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
      /**
       * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
       *
       * <pre>
       * Set the request/response compress type.
       * </pre>
       */
      public boolean hasCompressType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
       *
       * <pre>
       * Set the request/response compress type.
       * </pre>
       */
      public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType getCompressType() {
        return compressType_;
      }
      /**
       * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
       *
       * <pre>
       * Set the request/response compress type.
       * </pre>
       */
      public Builder setCompressType(com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        compressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .brpc.policy.SofaCompressType compress_type = 300;</code>
       *
       * <pre>
       * Set the request/response compress type.
       * </pre>
       */
      public Builder clearCompressType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        compressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
        onChanged();
        return this;
      }

      // optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;
      private com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType expectedResponseCompressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
      /**
       * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
       *
       * <pre>
       * Set the response compress type of user expected.
       * </pre>
       */
      public boolean hasExpectedResponseCompressType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
       *
       * <pre>
       * Set the response compress type of user expected.
       * </pre>
       */
      public com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType getExpectedResponseCompressType() {
        return expectedResponseCompressType_;
      }
      /**
       * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
       *
       * <pre>
       * Set the response compress type of user expected.
       * </pre>
       */
      public Builder setExpectedResponseCompressType(com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        expectedResponseCompressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;</code>
       *
       * <pre>
       * Set the response compress type of user expected.
       * </pre>
       */
      public Builder clearExpectedResponseCompressType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        expectedResponseCompressType_ = com.baidu.brpc.protocol.sofa.SofaRpcProto.SofaCompressType.SOFA_COMPRESS_TYPE_NONE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brpc.policy.SofaRpcMeta)
    }

    static {
      defaultInstance = new SofaRpcMeta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:brpc.policy.SofaRpcMeta)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_brpc_policy_SofaRpcMeta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_brpc_policy_SofaRpcMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025sofa_pbrpc_meta.proto\022\013brpc.policy\"\271\002\n" +
      "\013SofaRpcMeta\022+\n\004type\030\001 \002(\0162\035.brpc.policy" +
      ".SofaRpcMeta.Type\022\023\n\013sequence_id\030\002 \002(\004\022\016" +
      "\n\006method\030d \001(\t\022\017\n\006failed\030\310\001 \001(\010\022\023\n\nerror" +
      "_code\030\311\001 \001(\005\022\017\n\006reason\030\312\001 \001(\t\0225\n\rcompres" +
      "s_type\030\254\002 \001(\0162\035.brpc.policy.SofaCompress" +
      "Type\022G\n\037expected_response_compress_type\030" +
      "\255\002 \001(\0162\035.brpc.policy.SofaCompressType\"!\n" +
      "\004Type\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001*\244\001\n\020Sof" +
      "aCompressType\022\033\n\027SOFA_COMPRESS_TYPE_NONE",
      "\020\000\022\033\n\027SOFA_COMPRESS_TYPE_GZIP\020\001\022\033\n\027SOFA_" +
      "COMPRESS_TYPE_ZLIB\020\002\022\035\n\031SOFA_COMPRESS_TY" +
      "PE_SNAPPY\020\003\022\032\n\026SOFA_COMPRESS_TYPE_LZ4\020\004B" +
      ",\n\034com.baidu.brpc.protocol.sofaB\014SofaRpc" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_brpc_policy_SofaRpcMeta_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_brpc_policy_SofaRpcMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_brpc_policy_SofaRpcMeta_descriptor,
              new java.lang.String[] { "Type", "SequenceId", "Method", "Failed", "ErrorCode", "Reason", "CompressType", "ExpectedResponseCompressType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
